config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root "user#index"
  post '/user_code', to: 'user#user_code' , as: 'user_code'
  get '/user_code', to: 'user#show_warning' , as: 'show_warning'
  post '/verify_user', to: 'user#verify_user' , as: 'verify_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  require 'zensend'
  require "base64"

  #enter mobile number on index page
  def index

  end

  #send user code to mobile number
  def user_code
    random_str = [*('1'..'9')].sample(4).join
    client = ZenSend::Client.new("5pPy6oDeZgz9ZZ8YXxHfWQ")
    begin
       result = client.send_sms(
          originator: "447858302548",
          originator_type: 'msisdn',
          # Add your number here to send a message to yourself
          #The number should be in international format.
          #For example GB numbers will be 447400123456
          numbers: [params[:phone]],
          body: "Hello! Enter #{random_str} to verify your number"
    )
      @encoded_random_str =  Base64.encode64(random_str)
      flash[:notice] = 'A confirmation code has been sent on your mobile number sucessfully'
    rescue ZenSend::ZenSendException => e
        redirect_to :root, alert: "ZenSendException: #{e.parameter} => #{e.failcode}"
    end

  end

  #verify user code sent on mobile number
  def verify_user
    decoded_random_str = Base64.decode64(params[:code_sent])
    if params[:code] == decoded_random_str
      respond_to do |format|
        format.js
      end
    else
      root_redirection_alert("Oops! You have entered invalid code")
    end
  end

  def show_warning
    root_redirection_alert("Warning! You need to enter mobile number to get code")
  end

  private

  def root_redirection_alert(msg)
    redirect_to :root, alert: msg
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FonixTest</title>
    <%= csrf_meta_tags %>

    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="assets/intlTelInput-jquery.min.js"></script>
  </head>

  <body>
  <div id="notice_alert" style="margin-top:5%;margin-bottom: -20px" class="container">
    <% if notice %>
      <div class="alert alert-success alert-dismissable fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong></strong> <%= notice %>
      </div>
    <% elsif alert %>
      <div class="alert alert-danger alert-dismissable fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong> </strong> <%= alert %>
      </div>
    <% end %>
  </div>
  <%= yield %>
  </body>
</html>

app/views/user/index.html.erb
<div class="container">
  <%= form_tag user_code_path ,{:class => 'form-input'} do %>
    <h2 class="form-signin-heading">Enter your mobile number:</h2>
    <%= label_tag 'Mobile number', 'mobile number', class:'sr-only' %>
    <%= telephone_field_tag :phone, '+44', class:'form-control', placeholder: "e.g. +44 7127892536", required: "required", :maxlength => 15  %>
    <%= submit_tag  :Confirm, class: 'btn btn-lg btn-primary btn-block btn-margin'%>
  <% end %>
</div>

<script>
    $("#phone").intlTelInput({
        // whether or not to allow the dropdown
        allowDropdown: true,

// if there is just a dial code in the input: remove it on blur, and re-add it on focus
        autoHideDialCode: true,

// add a placeholder in the input with an example number for the selected country
        autoPlaceholder: "polite",

// modify the auto placeholder
        customPlaceholder: null,

// append menu to specified element
        dropdownContainer: null,

// don't display these countries
        excludeCountries: [],

// format the input value during initialisation and on setNumber
        formatOnDisplay: true,

// geoIp lookup function
        geoIpLookup: null,

// inject a hidden input with this name, and on submit, populate it with the result of getNumber
        hiddenInput: "",

// initial country
        initialCountry: "gb",

// localized country names e.g. { 'de': 'Deutschland' }
        localizedCountries: null,

// don't insert international dial codes
        nationalMode: false,

// display only these countries
        onlyCountries: [],

// number type to use for placeholders
        placeholderNumberType: "MOBILE",

// the countries at the top of the list. defaults to united states and united kingdom
        preferredCountries: [ "us", "gb" ],

// display the country dial code next to the selected flag so it's not part of the typed number
        separateDialCode: false,

// specify the path to the libphonenumber script to enable validation/formatting
        utilsScript: ""
    });
</script>

app/views/user/user_code.html.erb
<div class="container">
  <%= form_tag verify_user_path , :remote => true , :class => 'form-input', :id => 'form-code' do %>
    <h2 class="form-signin-heading">Enter code sent on your number:</h2>
    <%= hidden_field_tag :code_sent, @encoded_random_str %>
    <%= label_tag 'Code', 'code', class:'sr-only' %>
    <%= text_field_tag :code, nil, class:'form-control', :maxlength => 4 %>
    <%= submit_tag  :Confirm, class: 'btn btn-lg btn-primary btn-block btn-margin'%>

  <% end %>
</div>

<div class="container">
   <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Success</h4>
        </div>
        <div class="modal-body">
          <p>You have entered right code</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/user/verify_user.js.erb
$('#myModal').modal('show');